[build]
  publish = "."

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = """
      default-src 'self' https://identity.netlify.com https://unpkg.com https://www.youtube.com https://player.vimeo.com;
      img-src 'self' data: https://www.youtube.com https://i.vimeocdn.com;
      style-src 'self' 'unsafe-inline' https://unpkg.com;
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://identity.netlify.com https://unpkg.com https://www.youtube.com https://player.vimeo.com;
      connect-src 'self' https://identity.netlify.com;
      frame-src https://www.youtube.com https://player.vimeo.com;
    """
